export const MOCK_USER = {
    id: 'USR-83294',
    name: 'Amit Verma',
    deviceId: '#93304',
    messagesUsed: 2,
    messagesLimit: 3,
    isWorker: false,
    workerStatus: 'Inactive',
    joinedSocieties: ['soc1', 'soc2'],
};

export const MOCK_SOCIETIES = [
    {
        id: 'soc1',
        name: 'Green Park Society',
        location: 'Sector 4, New Delhi',
        memberCount: 124,
        flatNumber: 'Flat 402',
        role: 'admin',
        status: 'clean',
        statusLabel: 'Clean',
        image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80',
        slug: 'gP7xK2',
        isElectionDue: true,
        poolActive: true,
        poolAmount: '₹1500',
    },
    {
        id: 'soc2',
        name: 'Sunrise Colony',
        location: 'Sector 8, New Delhi',
        memberCount: 45,
        flatNumber: 'Flat 128',
        role: 'member',
        status: 'issue',
        statusLabel: 'Issue',
        image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=400&q=80',
        slug: 'sC3mN8',
        isElectionDue: false,
        poolActive: false,
        poolAmount: null,
    },
];

export const MOCK_ALERTS = [
    {
        id: 'alert1',
        type: 'election',
        title: 'Admin Rotation Pending',
        description: "It's your turn to manage this week's cleanup schedule for Greenwood Heights.",
        action: 'Review',
        societyId: 'soc1',
    },
    {
        id: 'alert2',
        type: 'pool',
        title: 'Monthly Pool Contribution',
        description: '₹500 contribution for waste management. See more in Due Submissions.',
        action: 'Pay',
        societyId: 'soc1',
    },
];

export const MOCK_POSTS = [
    {
        id: 'post1',
        author: 'Sarah Jenkins',
        flat: 'Block 4',
        timeAgo: '3 hours ago',
        content: "Garbage hasn't been collected from the back gate for 3 days, it's starting to smell really bad. Can we get this checked?",
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
        likes: 12,
        comments: 4,
        priority: 'HIGH',
        type: 'issue',
        societyId: 'soc1',
        status: 'Open',
    },
    {
        id: 'post2',
        author: 'Society Admin',
        flat: 'B-announcement',
        timeAgo: '5 hours ago',
        content: 'Great work team! The park entrance has been cleaned of debris. Here are the results.',
        beforeImage: 'https://images.unsplash.com/photo-1603715099925-da93b2b0b8e8?w=300&q=80',
        afterImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&q=80',
        likes: 24,
        comments: 8,
        type: 'before_after',
        priority: null,
        societyId: 'soc1',
        status: 'RESOLVED',
    },
    {
        id: 'post3',
        author: 'Maintenance Team',
        flat: 'B-announcement',
        timeAgo: 'Yesterday',
        content: 'Sanitation drive is scheduled for this Sunday at 7am. All members are requested to participate.',
        image: null,
        likes: 18,
        comments: 5,
        type: 'announcement',
        priority: null,
        societyId: 'soc1',
        status: null,
    },
];

export const MOCK_WORKERS = [
    {
        id: 'w1',
        name: 'Ramesh Kumar',
        specialty: 'Waste Management Specialist',
        area: 'Indiranagar',
        schedule: 'Mon-Fri, 8am-2pm',
        image: null,
        available: true,
        initials: 'RK',
        color: '#1A7A3C',
    },
    {
        id: 'w2',
        name: 'Sunita Devi',
        specialty: 'Community Cleaner',
        area: 'Koramangala 4th Block',
        schedule: 'Weekends Only',
        image: null,
        available: true,
        initials: 'SD',
        color: '#7B2FBE',
    },
    {
        id: 'w3',
        name: 'Vikram Singh',
        specialty: 'Heavy Lifting & Disposal',
        area: 'Domlur',
        schedule: 'Flexible',
        image: null,
        available: false,
        initials: 'VS',
        color: '#E07B00',
    },
    {
        id: 'w4',
        name: 'Priya Jaiswal',
        specialty: 'Gardening Assistant',
        area: 'HSR Layout',
        schedule: 'Afternoon',
        image: null,
        available: true,
        initials: 'PJ',
        color: '#1A6FA0',
    },
];
